### PR TITLE
Removed snapshots

### PR DESCRIPTION
**Pull request by KyleErwin**
Book was making reference to using snapshots when setting up. It has been updated to 2.0.1

### CODE REVIEW

**Review by gpampara — COMMENTED** [review]
Any way to make this a token we replace and set the value once in some config?

**Comment by KyleErwin** [comment]
I think it's possible. I'll come up with something.

**Comment by gpampara** [comment]
At the end of the day, the document is processed by `pandoc`, we can define variables for that quite simply.

**Comment by gpampara** [comment]
A better solution: https://www.scala-sbt.org/sbt-site/preprocess.html

Will create a PR

**Comment by gpampara** [comment]
Closed in favor of #8

**Pull request closed without merging**
